export const election = [
    '¿Hacer o que te hagan?',
    '¿Sexo oral o penetración?',
    '¿Sexo suave o sexo fuerte?',
    '¿Polvo de una hora o polvo rápido?',
    '¿Luz apagada o luz encendida?',
    '¿Solo gemidos o palabras sucias?',
    '¿Encima o debajo?',
    '¿Mañanero o nocturno?',
    '¿Silencioso o escandaloso?',
    '¿Cara bonita o cuerpo sexy?',
    '¿Misionero o perrito?',
    '¿Mirar o que te miren?',
    '¿Que Scarlett Johansson/Ryan Gosling te haga un striptease mientras Woody Allen te practica sexo oral, o que Woody Allen te haga un striptease mientras Scarlett Johansson/Ryan Gosling te practica sexo oral? No puedes mirar al que te practica sexo oral y estás obligado a mirar al que se desnuda para ti',
    '¿Cuerpo bonito y sexo mediocre o sexo increíble y cuerpo mediocre?',
    '¿Crees que eres un@ chic@ mal@ o un@ chic@ buen@?',
    '¿Porno amateur o profesional?',
];

export const questions = [
    '¿Cuál es la parte más sensible de tu cuerpo?',
    '¿Qué es lo que más te excita?',
    '¿Cuál es tu práctica sexual favorita?',
    '¿Tienes algun fetiche?',
    '¿Hay algo que no hayas probado y que quieras probar?',
    '¿En qué sitio te gustaría hacerlo y no has probado todavía?',
    '¿Hay alguna raza/etnia/nacionalidad que te atraiga especialmente?¿Y alguna que no?',
    '¿Si pudieras cambiar una parte de tu cuerpo cual sería?',
    '¿De qué parte de tu cuerpo estás especialmente orgullos@?',
    '¿Qué parte del cuerpo del otro sexo te atrae más?',
    '¿Con qué famoso tendrías sexo una noche?',
    '¿Con qué famoso tendrías una aventura prolongada en el tiempo?',
    '¿En sexo qué sentido eliminarias?',
    '¿Crees que el tamaño importa?',
    '¿Cada cuanto te masturbas?',
    '¿Ves pornografía con frecuencia?',
    'Descríbete sexualmente con 2 palabras',
    '¿Te gusta que te aten?',
    'Si pudieras ser del sexo opuesto durante un día entero ¿Qué harías?',
    '¿A quien no te gustaría ver desnudo?',
    '¿Qué escena sexy de una película te gusta más?',
    '¿Cual es tu edad límite para tener relaciones con una persona? Por arriba y por abajo',
    '¿Qué nota te pondrías en la cama?',
    '¿Eres celoso?',
    '¿Tienes algún nombre para tu zona especial?',
    '¿Utilizarías drogas para practicar sexo?',
    '¿Te gusta el BDSM? Real o vainilla',
    '¿Qué es lo mejor de ser hombre/mujer? En el sexo y fuera de él',
    '¿Qué es lo peor de se hombre/mujer? En el sexo y fuera de él',
    'En tu opinión ¿En qué consiste ser bueno en la cama?',
    '¿Cuál sería el regalo que te pondría más caliente?',
    '¿Tienes algún vídeo porno en concreto que sea tu favorito?',
    '¿Te gustan los juegos de rol? Sexualmente hablando',
    '¿Te excita escuchar a otras personas tener sexo?',
    '¿Cómo te estimulas cuando te masturbas?',
    '¿Te gusta hacer videos de tus relaciones sexuales?',
];

export const historic = [
    '¿Has mantenido relaciones en un sitio público?',
    '¿Cuál es el lugar más inusual en el que has tenido relaciones?',
    'Tres momentos sexuales memorables en tu vida',
    'Tres momentos sexuales horribles en tu vida',
    '¿Hay algún límite que ni con tu pareja has hecho?',
    '¿Te has acostado con alguien de otra raza/etnia/nacionalidad?',
    '¿Te has masturbado alguna vez en el trabajo?',
    '¿A qué edad perdiste la virginidad?',
    '¿Tienes alguna experiencia inconfesable?',
    '¿Recuerdas el mejor orgasmo que hayas tenido?',
    '¿Alguna vez te has arrepentido de acostarte con alguien?',
    '¿Cuantas veces te has despertado en una casa ajena sin recordar nada de la noche anterior?',
    '¿Te han pillado mientras estabas en la cama con otra persona?',
    '¿Cuanto tiempo has llegado a pasar sin hacerlo?',
    '¿Has tenido un sueño erótico con personas que no te atraian?',
    '¿Lo has hecho alguna vez al aire libre?',
    '¿Alguna vez has espiado a alguien teniendo sexo?',
    '¿Alguna vez has tenido sexo con alguien de quien nunca supiste su nombre?',
];

export const expectations = [
    '¿Qué es lo más te gustó de nosotros cuando nos conocimos?',
    '¿Cómo crees que es en la cama cada uno de la mesa?',
    '¿Te has masturbado pensando en esta noche?',
    'Cuando te has imaginado esta noche, ¿qué imagen te viene a la cabeza?',
    '¿Qué quieres hacer esta noche y es imprescindible?',
    '¿Hay algo que te preocupe o te asuste esta noche?',
];