import Head from 'next/head'
import styled from 'styled-components'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const Layout = styled.div`
  display:flex;
  flex-direction:column;
  align-items:center;
  justify-content:center;
  width:100%;
  height:100vh;
`;

const Button = styled.button`
  border-radius:25px;
  min-height:50px;
  color:white;
  background:linear-gradient(180deg, rgba(129,23,25,1) 0%, rgba(190,32,40,1) 100%);
  font-size:24px;
  min-width:300px;
  border: 0px;

`;

const Logo = styled.div`
  display:flex;
  width:50%;
  height:500px;
  background-image:url("/logo.png");
  background-size:contain;
  background-position:center;
  background-repeat:no-repeat;  
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Passion Cards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Logo />
        <a href="/random"><Button>
          Play
        </Button></a>

        

        
      </Layout>
    </>
  )
}
