import Head from 'next/head'
import Link from 'next/link'
import styled from 'styled-components'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from '@/components/atoms/Button'

const inter = Inter({ subsets: ['latin'] })

const Layout = styled.div`
  display:flex;
  flex-direction:column;
  align-items:center;
  justify-content:center;
  width:100%;
  height:100vh;
  gap: 10px;
  padding:20px;
`;

// const Button = styled.button`
//   border-radius:25px;
//   min-height:50px;
//   color:white;
//   background:linear-gradient(180deg, rgba(129,23,25,1) 0%, rgba(190,32,40,1) 100%);
//   font-size:24px;
//   min-width:300px;
//   border: 0px;
//   cursor: pointer;

// `;

const Logo = styled.div`
  display:flex;
  width:350px;
  height:350px;
  background-image:url("/PC_logo1.png");
  background-size:contain;
  background-position:center;
  background-repeat:no-repeat;
  margin-bottom:10px;
  
  @media (min-width:840px){
    width:350px;
    height:350px;
  }  
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Passion Cards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Logo />
        <Link href="/random"><Button>
          Play
        </Button></Link>
        <Link href="/addPlayers"><Button type="Secondary">
          Add Players
        </Button></Link>

        

        
      </Layout>
    </>
  )
}
